select tiss.* from (
select NR_PROTOCOLO_RECEBIMENTO, 
COUNT(*) 
from TISS_BATCH  where 
TIPO_TRANSACAO = 'PROTOCOLO_RECEBIMENTO' 
GROUP BY NR_PROTOCOLO_RECEBIMENTO 
HAVING COUNT(*) > 1) 
repetidos,TISS_BATCH tiss 
where tiss.NR_PROTOCOLO_RECEBIMENTO = repetidos.NR_PROTOCOLO_RECEBIMENTO 
order by tiss.NR_PROTOCOLO_RECEBIMENTO;